# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-14 21:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('desescuela', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('alias', models.CharField(max_length=30)),
                ('tel', models.CharField(max_length=15)),
                ('mail', models.EmailField(max_length=500)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Alumni',
                'verbose_name_plural': 'Alumnis',
            },
        ),
        migrations.CreateModel(
            name='AlumniInBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField()),
                ('alumni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumni', to='alumni.Alumni')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_alumni', to='desescuela.Batch')),
                ('cinta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cinta_alumni', to='desescuela.Cinta')),
            ],
            options={
                'verbose_name': 'AlumniInBatch',
                'verbose_name_plural': 'AlumniInBatch',
            },
        ),
    ]
