# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-14 22:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('desescuela', '0001_initial'),
        ('alumni', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumniinbatch',
            name='alumni',
        ),
        migrations.RemoveField(
            model_name='alumniinbatch',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='alumniinbatch',
            name='cinta',
        ),
        migrations.AddField(
            model_name='alumni',
            name='batch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='batch_alumni', to='desescuela.Batch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alumni',
            name='cinta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cinta_alumni', to='desescuela.Cinta'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AlumniInBatch',
        ),
    ]
